// =============================================================================
// Action: notify_call_security
// Generated by Builder AI from student_actions.dera
// Triggered when: graduate_student on student with academic = Suspended | Expelled
// Returns NoAction — graduation blocked. Side effect: alert notification.
// =============================================================================

import { PrismaClient } from '@prisma/client';
import type { ActionContext, ActionResult } from '../../shared/types';
import type { GraduateStudentInput } from '../student.types';

const prisma = new PrismaClient();

export async function notify_call_security(
  ctx: ActionContext<GraduateStudentInput>,
): Promise<ActionResult> {
  const { event } = ctx;
  const studentId = event.eventInput.studentId;

  const student = await prisma.student.findUnique({ where: { id: studentId } });

  // Side effect: alert administration
  try {
    console.log(`[notify_call_security] Alert: unauthorized graduation attempt for student ${studentId} (state: ${student?.academicState})`);
  } catch (err) {
    console.error(`[notify_call_security] Side effect failed:`, err);
  }

  return {
    outcome: 'NoAction',
    code: 'GRADUATION_BLOCKED',
    message: `Student ${studentId} cannot graduate in state ${student?.academicState}`,
  };
}
