// =============================================================================
// Action: notify_already_graduated
// Generated by Builder AI from student_actions.dera
// Triggered when: graduate_student on student with academic = Graduated
// Returns NoAction — student is already in target state.
// =============================================================================

import type { ActionContext, ActionResult } from '../../shared/types';
import type { GraduateStudentInput } from '../student.types';

export async function notify_already_graduated(
  ctx: ActionContext<GraduateStudentInput>,
): Promise<ActionResult> {
  const studentId = ctx.event.eventInput.studentId;

  return {
    outcome: 'NoAction',
    code: 'STUDENT_ALREADY_GRADUATED',
    message: `Student ${studentId} is already graduated`,
  };
}
