// =============================================================================
// Action: perform_send_grades_to_parents
// Generated by Builder AI from student_actions.dera
// Triggered when: send_grades_to_parents, academic = Active
// Side effect: email to parents via Resend / SendGrid
// =============================================================================

import { PrismaClient } from '@prisma/client';
import type { ActionContext, ActionResult } from '../../shared/types';
import type { SendGradesToParentsInput, SendGradesToParentsResult } from '../student.types';

const prisma = new PrismaClient();

export async function perform_send_grades_to_parents(
  ctx: ActionContext<SendGradesToParentsInput>,
): Promise<ActionResult<SendGradesToParentsResult>> {
  const { event } = ctx;
  const studentId = event.eventInput.studentId?.trim();

  if (!studentId) {
    return { outcome: 'ValidationFailure', code: 'VALIDATION_FAILED', message: 'studentId is required', failedValidations: [{ field: 'studentId', code: 'REQUIRED', message: 'studentId is required' }] };
  }

  const student = await prisma.student.findUnique({ where: { id: studentId } });
  if (!student) {
    return { outcome: 'ValidationFailure', code: 'STUDENT_NOT_FOUND', message: `Student ${studentId} does not exist`, failedValidations: [{ field: 'studentId', code: 'NOT_FOUND', message: `Student ${studentId} was not found` }] };
  }

  // Side effect: send email to parents
  const parentEmail = await getParentEmail(studentId);

  await sendGradesEmail(student.name, student.lastName, student.grade, parentEmail);

  return {
    outcome: 'Success',
    code: 'GRADES_SENT_TO_PARENTS',
    message: `Grades sent to parents of student ${studentId}`,
    data: { studentId, sentTo: parentEmail },
    changeLogs: [],
  };
}

async function getParentEmail(studentId: string): Promise<string> {
  // TODO: retrieve parent email from student profile or separate parent table
  return `parents_of_${studentId}@example.com`;
}

async function sendGradesEmail(name: string, lastName: string, grade: string, email: string): Promise<void> {
  // TODO: integrate with Resend (primary) / SendGrid (backup) per tech-stack.md
  console.log(`[sendGradesEmail] Sending grade report for ${name} ${lastName} (grade: ${grade}) to ${email}`);
}
