// =============================================================================
// Action: perform_student_creation
// Generated by Builder AI from student_actions.dera
//
// Triggered when: route_create_student (always — NewEntry pattern)
// Pattern:        NewEntry — creates a new Student record
//
// Full DERA action pipeline:
//   1. Sanitize       — normalize inputs
//   2. Validate       — check required fields and formats
//   3. Business Rules — verify no duplicates or spec preconditions
//   4. Execute        — insert new record into Persistence
//   5. Side Effects   — welcome notification
//
// Source: student_actions.dera → Action perform_student_creation
// =============================================================================

import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';
import type { ActionContext, ActionResult } from '../../shared/types';
import type { CreateStudentInput, CreateStudentResult, Grade, Group } from '../student.types';

const prisma = new PrismaClient();

const VALID_GRADES: Grade[] = ['First', 'Second', 'Third', 'Fourth', 'Fifth', 'Sixth'];
const VALID_GROUPS: Group[] = ['A', 'B', 'C'];

export async function perform_student_creation(
  ctx: ActionContext<CreateStudentInput>,
): Promise<ActionResult<CreateStudentResult>> {
  const { event } = ctx;
  const input = event.eventInput;

  // =========================================================================
  // STEP 1 — Sanitize
  // =========================================================================

  const name = input.name?.trim();
  const lastName = input.lastName?.trim();
  const grade = input.grade?.trim() as Grade;
  const group = input.group?.trim() as Group;
  const dateOfBirthRaw = input.dateOfBirth?.trim();

  // =========================================================================
  // STEP 2 — Validate
  // =========================================================================

  const failures: Array<{ field: string; code: string; message: string }> = [];

  if (!name) {
    failures.push({ field: 'name', code: 'REQUIRED', message: 'name is required' });
  }

  if (!lastName) {
    failures.push({ field: 'lastName', code: 'REQUIRED', message: 'lastName is required' });
  }

  if (!grade) {
    failures.push({ field: 'grade', code: 'REQUIRED', message: 'grade is required' });
  } else if (!VALID_GRADES.includes(grade)) {
    failures.push({
      field: 'grade',
      code: 'INVALID_VALUE',
      message: `grade must be one of: ${VALID_GRADES.join(', ')}`,
    });
  }

  if (!group) {
    failures.push({ field: 'group', code: 'REQUIRED', message: 'group is required' });
  } else if (!VALID_GROUPS.includes(group)) {
    failures.push({
      field: 'group',
      code: 'INVALID_VALUE',
      message: `group must be one of: ${VALID_GROUPS.join(', ')}`,
    });
  }

  if (!dateOfBirthRaw) {
    failures.push({ field: 'dateOfBirth', code: 'REQUIRED', message: 'dateOfBirth is required' });
  }

  let dateOfBirth: Date | undefined;
  if (dateOfBirthRaw) {
    dateOfBirth = new Date(dateOfBirthRaw);
    if (isNaN(dateOfBirth.getTime())) {
      failures.push({
        field: 'dateOfBirth',
        code: 'INVALID_FORMAT',
        message: 'dateOfBirth must be a valid ISO date (YYYY-MM-DD)',
      });
    }
  }

  if (failures.length > 0) {
    return {
      outcome: 'ValidationFailure',
      code: 'VALIDATION_FAILED',
      message: 'Input validation failed',
      failedValidations: failures,
    };
  }

  // =========================================================================
  // STEP 3 — Business Rules
  // From student_actions.dera: no duplicate student by name+lastName+dateOfBirth
  // =========================================================================

  const existing = await prisma.student.findFirst({
    where: {
      name: name!,
      lastName: lastName!,
      dateOfBirth: dateOfBirth!,
    },
  });

  if (existing) {
    return {
      outcome: 'ValidationFailure',
      code: 'STUDENT_ALREADY_EXISTS',
      message: `A student named ${name} ${lastName} born on ${dateOfBirthRaw} already exists`,
      failedValidations: [
        {
          field: 'name+lastName+dateOfBirth',
          code: 'DUPLICATE',
          message: 'A student with the same name and date of birth already exists',
        },
      ],
    };
  }

  // =========================================================================
  // STEP 4 — Execute
  // Create the Student record. Initial academicState = Active (spec default).
  // For NewEntry events, both createdByEventId and lastModifiedByEventId
  // are set to the creating event.
  // =========================================================================

  const studentId = randomUUID();

  await prisma.$transaction([
    prisma.student.create({
      data: {
        id: studentId,
        name: name!,
        lastName: lastName!,
        grade: grade!,
        group: group!,
        dateOfBirth: dateOfBirth!,
        academicState: 'Active',              // initial state per spec
        createdByEventId: event.eventId,
        lastModifiedByEventId: event.eventId,
      },
    }),

    // ChangeLog for NewEntry: oldValue = null (record did not exist before)
    prisma.changeLog.create({
      data: {
        eventId: event.eventId,
        entityType: 'Student',
        entityId: studentId,
        field: 'academicState',
        oldValue: null,
        newValue: 'Active',
        actorId: event.actorId,
      },
    }),
  ]);

  // =========================================================================
  // STEP 5 — Side Effects
  // Send welcome notification.
  // =========================================================================

  try {
    await sendWelcomeNotification(studentId, name!, lastName!);
  } catch (err) {
    console.error(`[perform_student_creation] Side effect failed for student ${studentId}:`, err);

    await prisma.errorLog.create({
      data: {
        eventId: event.eventId,
        errorType: 'SideEffectFailure',
        errorMessage: (err as Error).message,
        stackTrace: (err as Error).stack ?? '',
        serviceName: 'student-service',
        entityType: 'Student',
        entityId: studentId,
        environment: process.env.NODE_ENV ?? 'development',
      },
    });
  }

  // =========================================================================
  // Return ActionSuccess
  // =========================================================================

  return {
    outcome: 'Success',
    code: 'STUDENT_CREATED',
    message: `Student ${name} ${lastName} created successfully`,
    data: {
      studentId,
    },
    changeLogs: [
      {
        entityType: 'Student',
        entityId: studentId,
        field: 'academicState',
        oldValue: null,
        newValue: 'Active',
        actorId: event.actorId,
      },
    ],
  };
}

// =============================================================================
// Side Effect: sendWelcomeNotification
// =============================================================================

async function sendWelcomeNotification(
  studentId: string,
  name: string,
  lastName: string,
): Promise<void> {
  // TODO: integrate with Resend (primary) / SendGrid (backup) per tech-stack.md
  console.log(`[sendWelcomeNotification] Sending welcome email for ${name} ${lastName} (${studentId})`);
}
