// =============================================================================
// Action: perform_address_update
// Generated by Builder AI from student_actions.dera
// Pattern: DefaultAction — side-effect-only, no Student schema fields changed
// (address is stored in external address service, not in students table)
// =============================================================================

import { PrismaClient } from '@prisma/client';
import type { ActionContext, ActionResult } from '../../shared/types';
import type { UpdateStudentAddressInput, UpdateAddressResult } from '../student.types';

const prisma = new PrismaClient();

export async function perform_address_update(
  ctx: ActionContext<UpdateStudentAddressInput>,
): Promise<ActionResult<UpdateAddressResult>> {
  const { event } = ctx;
  const { studentId, street, city, postalCode } = event.eventInput;

  // Validate
  const failures = [];
  if (!studentId?.trim()) failures.push({ field: 'studentId', code: 'REQUIRED', message: 'studentId is required' });
  if (!street?.trim()) failures.push({ field: 'street', code: 'REQUIRED', message: 'street is required' });
  if (!city?.trim()) failures.push({ field: 'city', code: 'REQUIRED', message: 'city is required' });
  if (!postalCode?.trim()) failures.push({ field: 'postalCode', code: 'REQUIRED', message: 'postalCode is required' });
  if (failures.length > 0) return { outcome: 'ValidationFailure', code: 'VALIDATION_FAILED', message: 'Input validation failed', failedValidations: failures };

  // Business Rule: student must exist
  const student = await prisma.student.findUnique({ where: { id: studentId } });
  if (!student) {
    return { outcome: 'ValidationFailure', code: 'STUDENT_NOT_FOUND', message: `Student ${studentId} does not exist`, failedValidations: [{ field: 'studentId', code: 'NOT_FOUND', message: `Student ${studentId} was not found` }] };
  }

  // Execute — Side effect only: call external address service
  // No Student schema fields change. No ChangeLog entries written.
  try {
    await updateExternalAddressService(studentId, { street, city, postalCode });
  } catch (err) {
    await prisma.errorLog.create({
      data: {
        eventId: event.eventId,
        errorType: 'SideEffectFailure',
        errorMessage: (err as Error).message,
        stackTrace: (err as Error).stack ?? '',
        serviceName: 'student-service',
        entityType: 'Student',
        entityId: studentId,
        environment: process.env.NODE_ENV ?? 'development',
      },
    });
    throw err;  // propagate — address update is the core operation, not a side effect
  }

  return {
    outcome: 'Success',
    code: 'ADDRESS_UPDATED',
    message: `Address updated for student ${studentId}`,
    data: { studentId },
    changeLogs: [],  // address is not in Student schema
  };
}

async function updateExternalAddressService(
  studentId: string,
  address: { street: string; city: string; postalCode: string },
): Promise<void> {
  // TODO: integrate with address microservice
  console.log(`[updateExternalAddressService] Updating address for student ${studentId}:`, address);
}
