// =============================================================================
// Action: perform_set_grades
// Generated by Builder AI from student_actions.dera
// Pattern: DefaultAction — updates Grade catalog field, state-independent
// =============================================================================

import { PrismaClient } from '@prisma/client';
import type { ActionContext, ActionResult } from '../../shared/types';
import type { SetGradesToStudentInput, SetGradesResult, Grade } from '../student.types';

const prisma = new PrismaClient();
const VALID_GRADES: Grade[] = ['First', 'Second', 'Third', 'Fourth', 'Fifth', 'Sixth'];

export async function perform_set_grades(
  ctx: ActionContext<SetGradesToStudentInput>,
): Promise<ActionResult<SetGradesResult>> {
  const { event } = ctx;
  const { studentId, grade } = event.eventInput;

  // Validate
  const failures = [];
  if (!studentId?.trim()) failures.push({ field: 'studentId', code: 'REQUIRED', message: 'studentId is required' });
  if (!grade) failures.push({ field: 'grade', code: 'REQUIRED', message: 'grade is required' });
  else if (!VALID_GRADES.includes(grade)) {
    failures.push({ field: 'grade', code: 'INVALID_VALUE', message: `grade must be one of: ${VALID_GRADES.join(', ')}` });
  }
  if (failures.length > 0) return { outcome: 'ValidationFailure', code: 'VALIDATION_FAILED', message: 'Input validation failed', failedValidations: failures };

  // Load entity
  const student = await prisma.student.findUnique({ where: { id: studentId } });
  if (!student) {
    return { outcome: 'ValidationFailure', code: 'STUDENT_NOT_FOUND', message: `Student ${studentId} does not exist`, failedValidations: [{ field: 'studentId', code: 'NOT_FOUND', message: `Student ${studentId} was not found` }] };
  }

  const previousGrade = student.grade as Grade;

  // Execute
  await prisma.$transaction([
    prisma.student.update({
      where: { id: studentId },
      data: { grade, lastModifiedByEventId: event.eventId },
    }),
    prisma.changeLog.create({
      data: {
        eventId: event.eventId,
        entityType: 'Student',
        entityId: studentId,
        field: 'grade',
        oldValue: previousGrade,
        newValue: grade,
        actorId: event.actorId,
      },
    }),
  ]);

  return {
    outcome: 'Success',
    code: 'GRADE_UPDATED',
    message: `Grade updated for student ${studentId}`,
    data: { studentId, previousGrade, newGrade: grade },
    changeLogs: [{ entityType: 'Student', entityId: studentId, field: 'grade', oldValue: previousGrade, newValue: grade, actorId: event.actorId }],
  };
}
