// =============================================================================
// Action: perform_graduation
// Generated by Builder AI from student_actions.dera
//
// Triggered when: route_graduate_student returns 'perform_graduation'
// Condition:      academic = Active
//
// Full DERA action pipeline:
//   1. Sanitize    — normalize inputs
//   2. Validate    — check required fields and formats
//   3. Business Rules — verify spec preconditions
//   4. Execute     — apply state changes
//   5. Side Effects — notifications, external systems
//
// Source: student_actions.dera → Action perform_graduation
// =============================================================================

import { PrismaClient } from '@prisma/client';
import type { ActionContext, ActionResult, ChangeLogEntry } from '../../shared/types';
import type { GraduateStudentInput, GraduateStudentResult } from '../student.types';

const prisma = new PrismaClient();

export async function perform_graduation(
  ctx: ActionContext<GraduateStudentInput>,
): Promise<ActionResult<GraduateStudentResult>> {
  const { event } = ctx;
  const input = event.eventInput;

  // =========================================================================
  // STEP 1 — Sanitize
  // Normalize and clean inputs before any validation.
  // =========================================================================

  const studentId = input.studentId?.trim();

  // =========================================================================
  // STEP 2 — Validate
  // Check required fields and basic format constraints.
  // Returns ValidationFailure immediately if any field is invalid.
  // =========================================================================

  if (!studentId) {
    return {
      outcome: 'ValidationFailure',
      code: 'VALIDATION_FAILED',
      message: 'Input validation failed',
      failedValidations: [
        { field: 'studentId', code: 'REQUIRED', message: 'studentId is required' },
      ],
    };
  }

  // =========================================================================
  // STEP 3 — Business Rules
  // Load the entity and verify preconditions defined in the spec.
  // The rules engine already confirmed academic = Active before calling this
  // action, but we re-verify here for correctness and race condition safety.
  // =========================================================================

  const student = await prisma.student.findUnique({
    where: { id: studentId },
  });

  if (!student) {
    return {
      outcome: 'ValidationFailure',
      code: 'STUDENT_NOT_FOUND',
      message: `Student ${studentId} does not exist`,
      failedValidations: [
        { field: 'studentId', code: 'NOT_FOUND', message: `Student ${studentId} was not found` },
      ],
    };
  }

  // Re-verify state (defensive check against race conditions)
  if (student.academicState !== 'Active') {
    return {
      outcome: 'NoAction',
      code: 'STUDENT_NOT_ACTIVE',
      message: `Student ${studentId} is not in Active state (current: ${student.academicState})`,
    };
  }

  // =========================================================================
  // STEP 4 — Execute
  // Apply the state transition. Write Persistence + ChangeLog atomically.
  // =========================================================================

  const previousAcademicState = student.academicState;

  const changeLogs: ChangeLogEntry[] = [
    {
      entityType: 'Student',
      entityId: studentId,
      field: 'academicState',
      oldValue: previousAcademicState,
      newValue: 'Graduated',
      actorId: event.actorId,
    },
  ];

  await prisma.$transaction([
    // Update Persistence — Part 2 of DERA data model
    prisma.student.update({
      where: { id: studentId },
      data: {
        academicState: 'Graduated',
        lastModifiedByEventId: event.eventId,
      },
    }),

    // Write ChangeLog — Part 3 of DERA data model (one record per changed field)
    prisma.changeLog.create({
      data: {
        eventId: event.eventId,
        entityType: 'Student',
        entityId: studentId,
        field: 'academicState',
        oldValue: previousAcademicState,
        newValue: 'Graduated',
        actorId: event.actorId,
      },
    }),
  ]);

  // =========================================================================
  // STEP 5 — Side Effects
  // Non-blocking notifications and external system calls.
  // Failures here do not roll back the state change — they are logged separately.
  // Source: student_actions.dera → SideEffects block for perform_graduation
  // =========================================================================

  // Side effect: send graduation notification email to student and parents
  try {
    await sendGraduationNotification(studentId, student.name, student.lastName);
  } catch (err) {
    // Log side-effect failure without failing the main action
    // Monitor AI will detect this in ErrorLog if it becomes a pattern
    console.error(`[perform_graduation] Side effect failed for student ${studentId}:`, err);

    await prisma.errorLog.create({
      data: {
        eventId: event.eventId,
        errorType: 'SideEffectFailure',
        errorMessage: (err as Error).message,
        stackTrace: (err as Error).stack ?? '',
        serviceName: 'student-service',
        entityType: 'Student',
        entityId: studentId,
        environment: process.env.NODE_ENV ?? 'development',
      },
    });
  }

  // =========================================================================
  // Return ActionSuccess
  // =========================================================================

  return {
    outcome: 'Success',
    code: 'STUDENT_GRADUATED',
    message: `Student ${studentId} has been graduated successfully`,
    data: {
      studentId,
      previousAcademicState,
      newAcademicState: 'Graduated',
    },
    changeLogs,
  };
}

// =============================================================================
// Side Effect: sendGraduationNotification
// Sends graduation email via Resend (primary) with SendGrid as backup.
// Declared in student_actions.dera SideEffects block.
// =============================================================================

async function sendGraduationNotification(
  studentId: string,
  name: string,
  lastName: string,
): Promise<void> {
  // TODO: integrate with Resend (primary) and SendGrid (backup)
  // as declared in tech-stack.md Notifications section
  console.log(`[sendGraduationNotification] Sending graduation email for ${name} ${lastName} (${studentId})`);
}
