// =============================================================================
// Action: perform_check_grades
// Generated by Builder AI from student_actions.dera
// Pattern: DefaultAction — read-only, state-independent
// =============================================================================

import { PrismaClient } from '@prisma/client';
import type { ActionContext, ActionResult } from '../../shared/types';
import type { CheckGradesInput, CheckGradesResult } from '../student.types';

const prisma = new PrismaClient();

export async function perform_check_grades(
  ctx: ActionContext<CheckGradesInput>,
): Promise<ActionResult<CheckGradesResult>> {
  const { event } = ctx;
  const studentId = event.eventInput.studentId?.trim();

  // Validate
  if (!studentId) {
    return {
      outcome: 'ValidationFailure',
      code: 'VALIDATION_FAILED',
      message: 'Input validation failed',
      failedValidations: [{ field: 'studentId', code: 'REQUIRED', message: 'studentId is required' }],
    };
  }

  // Load entity
  const student = await prisma.student.findUnique({ where: { id: studentId } });
  if (!student) {
    return {
      outcome: 'ValidationFailure',
      code: 'STUDENT_NOT_FOUND',
      message: `Student ${studentId} does not exist`,
      failedValidations: [{ field: 'studentId', code: 'NOT_FOUND', message: `Student ${studentId} was not found` }],
    };
  }

  // Read-only — no Persistence or ChangeLog writes
  return {
    outcome: 'Success',
    code: 'GRADES_RETRIEVED',
    message: `Grades for student ${studentId} retrieved successfully`,
    data: {
      studentId: student.id,
      name: student.name,
      lastName: student.lastName,
      grade: student.grade as CheckGradesResult['grade'],
      group: student.group as CheckGradesResult['group'],
      academicState: student.academicState as CheckGradesResult['academicState'],
    },
    changeLogs: [],  // no changes — read-only action
  };
}
