// =============================================================================
// Action: reject_request
// Generated by Builder AI from student_actions.dera
// DefaultAction safety net — reached when no When rule matched.
// Should never be reached if spec covers all states, but required by spec.
// =============================================================================

import type { ActionContext, ActionResult } from '../../shared/types';

export async function reject_request(ctx: ActionContext): Promise<ActionResult> {
  return {
    outcome: 'NoAction',
    code: 'REQUEST_REJECTED',
    message: 'Request could not be processed in the current entity state',
  };
}
