// =============================================================================
// Action: skip_send_grades
// Generated by Builder AI from student_actions.dera
// Triggered when: send_grades_to_parents on non-Active student
// Returns NoAction silently — non-active students do not receive grade reports.
// =============================================================================

import type { ActionContext, ActionResult } from '../../shared/types';
import type { SendGradesToParentsInput } from '../student.types';

export async function skip_send_grades(
  ctx: ActionContext<SendGradesToParentsInput>,
): Promise<ActionResult> {
  const studentId = ctx.event.eventInput.studentId;

  return {
    outcome: 'NoAction',
    code: 'GRADES_SEND_SKIPPED',
    message: `Student ${studentId} is not active — grade report skipped`,
  };
}
