// =============================================================================
// Student Rules Engine
// Generated by Builder AI from student_rules.dera
//
// Implements the three DERA routing patterns:
//   1. NewEntry       — creates a new entity record (no state evaluation)
//   2. When clauses   — routes based on entity state (first rule wins)
//   3. DefaultAction  — state-independent operation on existing entity
//
// Rule: this module only determines WHICH action to call.
// It never executes business logic. It never modifies data.
// =============================================================================

import type { StudentRecord } from './student.types';

// -----------------------------------------------------------------------------
// Action name literals — every name matches an action file in ./actions/
// -----------------------------------------------------------------------------

export type StudentAction =
  | 'perform_student_creation'
  | 'perform_check_grades'
  | 'perform_graduation'
  | 'notify_already_graduated'
  | 'notify_call_security'
  | 'reject_request'
  | 'perform_set_grades'
  | 'perform_address_update'
  | 'perform_send_grades_to_parents'
  | 'skip_send_grades';

// -----------------------------------------------------------------------------
// Route result — the rules engine returns an action name or null
// null means no rule matched (should not happen if spec is complete)
// -----------------------------------------------------------------------------

export interface RouteResult {
  action: StudentAction;
  reason: string;   // human-readable explanation for logging
}

// =============================================================================
// Event: create_student
// Pattern: NewEntry — no entity record exists yet, no state evaluation
// Rule:    NewEntry → Action perform_student_creation
// Source:  student_rules.dera, line 1–2
// =============================================================================

export function route_create_student(): RouteResult {
  return {
    action: 'perform_student_creation',
    reason: 'NewEntry: creates new student record',
  };
}

// =============================================================================
// Event: check_grades
// Pattern: DefaultAction — state-independent operation on existing entity
// Rule:    DefaultAction → Action perform_check_grades
// Source:  student_rules.dera, line 5–6
// =============================================================================

export function route_check_grades(): RouteResult {
  return {
    action: 'perform_check_grades',
    reason: 'DefaultAction: reads current grades regardless of state',
  };
}

// =============================================================================
// Event: graduate_student
// Pattern: When clauses — state-based routing, first rule wins
//
// When  academic = Active     → Action perform_graduation
// When  academic = Graduated  → Action notify_already_graduated
// When  academic = Suspended  → Action notify_call_security
// When  academic = Expelled   → Action notify_call_security
// DefaultAction               → Action reject_request
//
// Source: student_rules.dera, lines 9–15
// =============================================================================

export function route_graduate_student(student: StudentRecord): RouteResult {
  // First rule: academic = Active
  if (student.academicState === 'Active') {
    return {
      action: 'perform_graduation',
      reason: `When academic = Active: student ${student.id} eligible for graduation`,
    };
  }

  // Second rule: academic = Graduated
  if (student.academicState === 'Graduated') {
    return {
      action: 'notify_already_graduated',
      reason: `When academic = Graduated: student ${student.id} is already graduated`,
    };
  }

  // Third rule: academic = Suspended
  if (student.academicState === 'Suspended') {
    return {
      action: 'notify_call_security',
      reason: `When academic = Suspended: student ${student.id} cannot graduate while suspended`,
    };
  }

  // Fourth rule: academic = Expelled
  if (student.academicState === 'Expelled') {
    return {
      action: 'notify_call_security',
      reason: `When academic = Expelled: student ${student.id} cannot graduate while expelled`,
    };
  }

  // DefaultAction — should not be reached if all states are covered,
  // but required by spec as a safety net for unhandled state values
  return {
    action: 'reject_request',
    reason: `DefaultAction: unhandled academic state "${student.academicState}" for student ${student.id}`,
  };
}

// =============================================================================
// Event: set_grades_to_student
// Pattern: DefaultAction — state-independent
// Rule:    DefaultAction → Action perform_set_grades
// Source:  student_rules.dera
// =============================================================================

export function route_set_grades_to_student(): RouteResult {
  return {
    action: 'perform_set_grades',
    reason: 'DefaultAction: updates student grade regardless of state',
  };
}

// =============================================================================
// Event: update_student_address
// Pattern: DefaultAction — state-independent
// Rule:    DefaultAction → Action perform_address_update
// Source:  student_rules.dera
// =============================================================================

export function route_update_student_address(): RouteResult {
  return {
    action: 'perform_address_update',
    reason: 'DefaultAction: updates student address regardless of state',
  };
}

// =============================================================================
// Event: send_grades_to_parents_on_first_day_of_month
// Pattern: When clauses — state-based routing
//
// When  academic = Active    → Action perform_send_grades_to_parents
// When  academic = Graduated → Action skip_send_grades
// When  academic = Suspended → Action skip_send_grades
// When  academic = Expelled  → Action skip_send_grades
// DefaultAction              → Action skip_send_grades
//
// Source: student_rules.dera
// =============================================================================

export function route_send_grades_to_parents(student: StudentRecord): RouteResult {
  // Only active students receive grade reports
  if (student.academicState === 'Active') {
    return {
      action: 'perform_send_grades_to_parents',
      reason: `When academic = Active: student ${student.id} is active, send grades to parents`,
    };
  }

  // All other states: skip silently
  return {
    action: 'skip_send_grades',
    reason: `DefaultAction: student ${student.id} has state "${student.academicState}", skipping grade report`,
  };
}
