// =============================================================================
// Student Entity — Types
// Generated by Builder AI from student_entity.dera and student_events.dera
// =============================================================================

// -----------------------------------------------------------------------------
// Catalogs — from student_entity.dera Catalogs section
// -----------------------------------------------------------------------------

export type Grade = 'First' | 'Second' | 'Third' | 'Fourth' | 'Fifth' | 'Sixth';

export type Group = 'A' | 'B' | 'C';

// -----------------------------------------------------------------------------
// State Dimensions — from student_entity.dera States section
// Evaluated by the rules engine at runtime to determine action routing.
// -----------------------------------------------------------------------------

export type AcademicState = 'Active' | 'Graduated' | 'Suspended' | 'Expelled';

// -----------------------------------------------------------------------------
// Student Persistence Record — from student_entity.dera Schema section
// Reflects Part 2 (Persistence) of the DERA data model.
// -----------------------------------------------------------------------------

export interface StudentRecord {
  id: string;
  name: string;
  lastName: string;
  grade: Grade;
  group: Group;
  dateOfBirth: Date;

  // State dimensions
  academicState: AcademicState;

  // DERA audit fields
  createdAt: Date;
  updatedAt: Date;
  createdByEventId: string;
  lastModifiedByEventId: string;
}

// -----------------------------------------------------------------------------
// Event Inputs — from student_events.dera
// Each event has exactly the fields declared in its EventInput block.
// -----------------------------------------------------------------------------

// create_student — NewEntry event. No student_id in input.
export interface CreateStudentInput {
  name: string;
  lastName: string;
  grade: Grade;
  group: Group;
  dateOfBirth: string;   // ISO date string, validated to Date in action
}

// check_grades — DefaultAction event. Requires student_id.
export interface CheckGradesInput {
  studentId: string;
}

// graduate_student — When event. Requires student_id.
export interface GraduateStudentInput {
  studentId: string;
}

// set_grades_to_student — DefaultAction event.
export interface SetGradesToStudentInput {
  studentId: string;
  grade: Grade;
}

// update_student_address — DefaultAction event.
// Note: address is not stored in current schema — this is a side-effect-only action
// (sends to external address service). No address fields in Student schema.
export interface UpdateStudentAddressInput {
  studentId: string;
  street: string;
  city: string;
  postalCode: string;
}

// send_grades_to_parents_on_first_day_of_month — When event (system-triggered).
export interface SendGradesToParentsInput {
  studentId: string;
}

// -----------------------------------------------------------------------------
// Action Result Data — what each successful action returns in EventResult.data
// Derived from student_actions.dera ActionResult sections.
// -----------------------------------------------------------------------------

export interface CreateStudentResult {
  studentId: string;
}

export interface CheckGradesResult {
  studentId: string;
  name: string;
  lastName: string;
  grade: Grade;
  group: Group;
  academicState: AcademicState;
}

export interface GraduateStudentResult {
  studentId: string;
  previousAcademicState: AcademicState;
  newAcademicState: AcademicState;
}

export interface SetGradesResult {
  studentId: string;
  previousGrade: Grade;
  newGrade: Grade;
}

export interface UpdateAddressResult {
  studentId: string;
}

export interface SendGradesToParentsResult {
  studentId: string;
  sentTo: string;    // parent email (from side effect)
}
