// =============================================================================
// Student Routes — Fastify HTTP Transport Layer
// Generated by Builder AI from student_events.dera and actors.dera
//
// This file is the transport layer only. It:
//   1. Receives HTTP requests
//   2. Checks idempotency (EventId already processed → return stored result)
//   3. Stores the EventRequest record
//   4. Calls the rules engine to determine the action
//   5. Calls the action
//   6. Stores the EventResult
//   7. Returns the EventResult as the HTTP response
//
// Domain logic lives in student.rules.ts and ./actions/*.
// This file never contains business logic.
// =============================================================================

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';

import type { IncomingEvent, EventResult } from '../shared/types';
import type {
  CreateStudentInput,
  CheckGradesInput,
  GraduateStudentInput,
  SetGradesToStudentInput,
  UpdateStudentAddressInput,
  SendGradesToParentsInput,
} from './student.types';

import {
  route_create_student,
  route_check_grades,
  route_graduate_student,
  route_set_grades_to_student,
  route_update_student_address,
  route_send_grades_to_parents,
} from './student.rules';

import { perform_student_creation } from './actions/perform_student_creation';
import { perform_check_grades } from './actions/perform_check_grades';
import { perform_graduation } from './actions/perform_graduation';
import { notify_already_graduated } from './actions/notify_already_graduated';
import { notify_call_security } from './actions/notify_call_security';
import { reject_request } from './actions/reject_request';
import { perform_set_grades } from './actions/perform_set_grades';
import { perform_address_update } from './actions/perform_address_update';
import { perform_send_grades_to_parents } from './actions/perform_send_grades_to_parents';
import { skip_send_grades } from './actions/skip_send_grades';

const prisma = new PrismaClient();

// =============================================================================
// Idempotency check
// If this EventId was already processed, return the stored result immediately.
// This is DERA's idempotency guarantee — same EventId never executes twice.
// =============================================================================

async function checkIdempotency(eventId: string): Promise<EventResult | null> {
  const existing = await prisma.eventResult.findUnique({
    where: { eventId },
  });

  if (!existing) return null;

  return {
    eventId: existing.eventId,
    outcome: existing.outcome as EventResult['outcome'],
    code: existing.code,
    message: existing.message,
    data: existing.data ?? undefined,
    failedValidations: (existing.failedValidations as EventResult['failedValidations']) ?? undefined,
    warnings: (existing.warnings as EventResult['warnings']) ?? undefined,
    traceId: existing.traceId,
    executedAt: existing.executedAt.toISOString(),
    durationMs: existing.durationMs,
  };
}

// =============================================================================
// Store EventRequest (Part 1 of DERA data model)
// =============================================================================

async function storeEventRequest<TInput>(event: IncomingEvent<TInput>): Promise<void> {
  await prisma.eventRequest.create({
    data: {
      id: event.eventId,
      traceId: event.traceId,
      correlationId: event.correlationId,
      actorId: event.actorId,
      eventType: event.eventType,
      entityId: event.entityId ?? null,
      eventInput: event.eventInput as object,
      status: 'Processing',
    },
  });
}

// =============================================================================
// Store EventResult and mark EventRequest as Completed/Failed (Parts 1 + 4)
// =============================================================================

async function storeEventResult(
  eventId: string,
  result: EventResult,
  outcome: 'Completed' | 'Failed',
): Promise<void> {
  await prisma.$transaction([
    prisma.eventResult.create({
      data: {
        eventId: result.eventId,
        outcome: result.outcome,
        code: result.code,
        message: result.message,
        data: result.data ?? undefined,
        failedValidations: result.failedValidations ?? undefined,
        warnings: result.warnings ?? undefined,
        traceId: result.traceId,
        durationMs: result.durationMs,
      },
    }),
    prisma.eventRequest.update({
      where: { id: eventId },
      data: {
        status: outcome,
        completedAt: new Date(),
      },
    }),
  ]);
}

// =============================================================================
// Core event handler — used by all routes
// Handles the full DERA event processing pipeline.
// =============================================================================

async function handleStudentEvent<TInput>(
  event: IncomingEvent<TInput>,
  reply: FastifyReply,
  processEvent: (event: IncomingEvent<TInput>) => Promise<EventResult>,
): Promise<void> {
  // 1. Idempotency check
  const cached = await checkIdempotency(event.eventId);
  if (cached) {
    reply.status(200).send(cached);
    return;
  }

  // 2. Store EventRequest
  await storeEventRequest(event);

  let result: EventResult;

  try {
    // 3. Execute rules + action
    result = await processEvent(event);

    // 4. Store result
    await storeEventResult(
      event.eventId,
      result,
      result.outcome === 'SystemError' ? 'Failed' : 'Completed',
    );
  } catch (err) {
    // Unhandled exception — write to ErrorLog and return SystemError
    const error = err as Error;

    await prisma.errorLog.create({
      data: {
        eventId: event.eventId,
        errorType: error.constructor.name,
        errorMessage: error.message,
        stackTrace: error.stack ?? '',
        serviceName: 'student-service',
        entityType: 'Student',
        entityId: event.entityId ?? null,
        environment: process.env.NODE_ENV ?? 'development',
      },
    });

    result = {
      eventId: event.eventId,
      outcome: 'SystemError',
      code: 'INTERNAL_ERROR',
      message: 'An unexpected error occurred',
      traceId: event.traceId,
      executedAt: new Date().toISOString(),
      durationMs: 0,
    };

    await storeEventResult(event.eventId, result, 'Failed');
  }

  const httpStatus =
    result.outcome === 'Success' ? 200 :
    result.outcome === 'ValidationFailure' ? 422 :
    result.outcome === 'NoAction' ? 200 :
    500;

  reply.status(httpStatus).send(result);
}

// =============================================================================
// Route Registration
// =============================================================================

export async function studentRoutes(fastify: FastifyInstance): Promise<void> {

  // ---------------------------------------------------------------------------
  // POST /students
  // Event: create_student — NewEntry pattern
  // Actor: Teacher
  // ---------------------------------------------------------------------------

  fastify.post<{ Body: Omit<CreateStudentInput, never> }>(
    '/students',
    async (request: FastifyRequest, reply: FastifyReply) => {
      const body = request.body as CreateStudentInput;

      const event: IncomingEvent<CreateStudentInput> = {
        eventId: randomUUID(),
        traceId: (request.headers['x-trace-id'] as string) ?? randomUUID(),
        correlationId: (request.headers['x-correlation-id'] as string) ?? randomUUID(),
        actorId: (request as unknown as { user: { sub: string } }).user?.sub ?? 'unknown',
        eventType: 'create_student',
        eventInput: body,
      };

      await handleStudentEvent(event, reply, async (evt) => {
        const routing = route_create_student();
        const startedAt = new Date();
        const actionResult = await perform_student_creation({ event: evt, startedAt });
        return buildEventResult(evt, actionResult, startedAt);
      });
    },
  );

  // ---------------------------------------------------------------------------
  // GET /students/:studentId/grades
  // Event: check_grades — DefaultAction pattern
  // Actor: Student, Teacher
  // ---------------------------------------------------------------------------

  fastify.get<{ Params: { studentId: string } }>(
    '/students/:studentId/grades',
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { studentId } = request.params as { studentId: string };

      const event: IncomingEvent<CheckGradesInput> = {
        eventId: (request.headers['x-event-id'] as string) ?? randomUUID(),
        traceId: (request.headers['x-trace-id'] as string) ?? randomUUID(),
        correlationId: (request.headers['x-correlation-id'] as string) ?? randomUUID(),
        actorId: (request as unknown as { user: { sub: string } }).user?.sub ?? 'unknown',
        eventType: 'check_grades',
        entityId: studentId,
        eventInput: { studentId },
      };

      await handleStudentEvent(event, reply, async (evt) => {
        route_check_grades();  // DefaultAction — no student needed for routing
        const startedAt = new Date();
        const actionResult = await perform_check_grades({ event: evt, startedAt });
        return buildEventResult(evt, actionResult, startedAt);
      });
    },
  );

  // ---------------------------------------------------------------------------
  // POST /students/:studentId/graduate
  // Event: graduate_student — When pattern (state-based routing)
  // Actor: Agent
  // ---------------------------------------------------------------------------

  fastify.post<{ Params: { studentId: string } }>(
    '/students/:studentId/graduate',
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { studentId } = request.params as { studentId: string };

      const event: IncomingEvent<GraduateStudentInput> = {
        eventId: (request.headers['x-event-id'] as string) ?? randomUUID(),
        traceId: (request.headers['x-trace-id'] as string) ?? randomUUID(),
        correlationId: (request.headers['x-correlation-id'] as string) ?? randomUUID(),
        actorId: (request as unknown as { user: { sub: string } }).user?.sub ?? 'unknown',
        eventType: 'graduate_student',
        entityId: studentId,
        eventInput: { studentId },
      };

      await handleStudentEvent(event, reply, async (evt) => {
        // When pattern: must load entity to evaluate state
        const student = await prisma.student.findUnique({ where: { id: studentId } });
        if (!student) {
          const startedAt = new Date();
          return buildNotFoundResult(evt, 'Student', studentId, startedAt);
        }

        const routing = route_graduate_student(student as unknown as Parameters<typeof route_graduate_student>[0]);
        const startedAt = new Date();

        switch (routing.action) {
          case 'perform_graduation':
            return buildEventResult(evt, await perform_graduation({ event: evt, startedAt }), startedAt);
          case 'notify_already_graduated':
            return buildEventResult(evt, await notify_already_graduated({ event: evt, startedAt }), startedAt);
          case 'notify_call_security':
            return buildEventResult(evt, await notify_call_security({ event: evt, startedAt }), startedAt);
          default:
            return buildEventResult(evt, await reject_request({ event: evt, startedAt }), startedAt);
        }
      });
    },
  );

  // ---------------------------------------------------------------------------
  // PATCH /students/:studentId/grade
  // Event: set_grades_to_student — DefaultAction pattern
  // Actor: Teacher
  // ---------------------------------------------------------------------------

  fastify.patch<{ Params: { studentId: string }; Body: { grade: string } }>(
    '/students/:studentId/grade',
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { studentId } = request.params as { studentId: string };
      const body = request.body as { grade: string };

      const event: IncomingEvent<SetGradesToStudentInput> = {
        eventId: (request.headers['x-event-id'] as string) ?? randomUUID(),
        traceId: (request.headers['x-trace-id'] as string) ?? randomUUID(),
        correlationId: (request.headers['x-correlation-id'] as string) ?? randomUUID(),
        actorId: (request as unknown as { user: { sub: string } }).user?.sub ?? 'unknown',
        eventType: 'set_grades_to_student',
        entityId: studentId,
        eventInput: { studentId, grade: body.grade as SetGradesToStudentInput['grade'] },
      };

      await handleStudentEvent(event, reply, async (evt) => {
        route_set_grades_to_student();
        const startedAt = new Date();
        const actionResult = await perform_set_grades({ event: evt, startedAt });
        return buildEventResult(evt, actionResult, startedAt);
      });
    },
  );

  // ---------------------------------------------------------------------------
  // PATCH /students/:studentId/address
  // Event: update_student_address — DefaultAction pattern
  // Actor: Teacher
  // ---------------------------------------------------------------------------

  fastify.patch<{ Params: { studentId: string }; Body: Omit<UpdateStudentAddressInput, 'studentId'> }>(
    '/students/:studentId/address',
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { studentId } = request.params as { studentId: string };
      const body = request.body as Omit<UpdateStudentAddressInput, 'studentId'>;

      const event: IncomingEvent<UpdateStudentAddressInput> = {
        eventId: (request.headers['x-event-id'] as string) ?? randomUUID(),
        traceId: (request.headers['x-trace-id'] as string) ?? randomUUID(),
        correlationId: (request.headers['x-correlation-id'] as string) ?? randomUUID(),
        actorId: (request as unknown as { user: { sub: string } }).user?.sub ?? 'unknown',
        eventType: 'update_student_address',
        entityId: studentId,
        eventInput: { studentId, ...body },
      };

      await handleStudentEvent(event, reply, async (evt) => {
        route_update_student_address();
        const startedAt = new Date();
        const actionResult = await perform_address_update({ event: evt, startedAt });
        return buildEventResult(evt, actionResult, startedAt);
      });
    },
  );

  // ---------------------------------------------------------------------------
  // POST /students/:studentId/send-grades
  // Event: send_grades_to_parents_on_first_day_of_month — When pattern
  // Actor: Agent (system-triggered)
  // ---------------------------------------------------------------------------

  fastify.post<{ Params: { studentId: string } }>(
    '/students/:studentId/send-grades',
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { studentId } = request.params as { studentId: string };

      const event: IncomingEvent<SendGradesToParentsInput> = {
        eventId: (request.headers['x-event-id'] as string) ?? randomUUID(),
        traceId: (request.headers['x-trace-id'] as string) ?? randomUUID(),
        correlationId: (request.headers['x-correlation-id'] as string) ?? randomUUID(),
        actorId: (request as unknown as { user: { sub: string } }).user?.sub ?? 'system-agent',
        eventType: 'send_grades_to_parents_on_first_day_of_month',
        entityId: studentId,
        eventInput: { studentId },
      };

      await handleStudentEvent(event, reply, async (evt) => {
        const student = await prisma.student.findUnique({ where: { id: studentId } });
        if (!student) {
          const startedAt = new Date();
          return buildNotFoundResult(evt, 'Student', studentId, startedAt);
        }

        const routing = route_send_grades_to_parents(student as unknown as Parameters<typeof route_send_grades_to_parents>[0]);
        const startedAt = new Date();

        switch (routing.action) {
          case 'perform_send_grades_to_parents':
            return buildEventResult(evt, await perform_send_grades_to_parents({ event: evt, startedAt }), startedAt);
          default:
            return buildEventResult(evt, await skip_send_grades({ event: evt, startedAt }), startedAt);
        }
      });
    },
  );
}

// =============================================================================
// Helpers
// =============================================================================

function buildEventResult<TInput>(
  event: IncomingEvent<TInput>,
  actionResult: Awaited<ReturnType<typeof perform_graduation>>,
  startedAt: Date,
): EventResult {
  const durationMs = Date.now() - startedAt.getTime();

  return {
    eventId: event.eventId,
    outcome: actionResult.outcome,
    code: actionResult.code,
    message: actionResult.message,
    data: 'data' in actionResult ? actionResult.data : undefined,
    failedValidations: 'failedValidations' in actionResult ? actionResult.failedValidations : undefined,
    traceId: event.traceId,
    executedAt: new Date().toISOString(),
    durationMs,
  };
}

function buildNotFoundResult<TInput>(
  event: IncomingEvent<TInput>,
  entityType: string,
  entityId: string,
  startedAt: Date,
): EventResult {
  return {
    eventId: event.eventId,
    outcome: 'ValidationFailure',
    code: `${entityType.toUpperCase()}_NOT_FOUND`,
    message: `${entityType} with id ${entityId} was not found`,
    failedValidations: [
      { field: 'entityId', code: 'NOT_FOUND', message: `${entityType} ${entityId} does not exist` },
    ],
    traceId: event.traceId,
    executedAt: new Date().toISOString(),
    durationMs: Date.now() - startedAt.getTime(),
  };
}
